name: 图床更新
on:
  release:
    types: [published]

jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
    - name: 检出
      uses: actions/checkout@master
    
    - name: 安装依赖
      run: yarn

    - name: 更新列表
      run: node main.js

    - name: 写 public key
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
    
    - name: 获取 npmrc
      run: cat .npmrc

    - name: 发布
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: 清理文件
      run: node clear.js

    - name: 更新 github 仓库
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: .
